<a href="https://colab.research.google.com/github/code-r28/Dev/blob/main/Coding_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
A=np.arange(1,17).reshape(4,4)

#Transpose Matrix

In [ ]:
print("Matrix")

Matrix


In [ ]:
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print("Transpose of the Matrix")

Transpose of the Matrix


In [ ]:
print(A.transpose())

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


#Matrix Multiplication

In [ ]:
B=np.arange(18,34).reshape(4,4)

In [ ]:
A.dot(B) #Multiplcation function

array([[ 260,  270,  280,  290],
       [ 644,  670,  696,  722],
       [1028, 1070, 1112, 1154],
       [1412, 1470, 1528, 1586]])

In [ ]:
C=np.arange(35,51).reshape(4,4)

In [ ]:
# ABC=(AB)C=A(BC)
temp1=(A.dot(B).dot(C))
temp2=A.dot((B).dot(C))

In [ ]:
print(temp1)
print(temp2)

[[ 45300  46400  47500  48600]
 [112532 115264 117996 120728]
 [179764 184128 188492 192856]
 [246996 252992 258988 264984]]
[[ 45300  46400  47500  48600]
 [112532 115264 117996 120728]
 [179764 184128 188492 192856]
 [246996 252992 258988 264984]]


#Inverse Matrix

In [ ]:
arr=np.arange(91,107).reshape(4,4)
print(arr)

[[ 91  92  93  94]
 [ 95  96  97  98]
 [ 99 100 101 102]
 [103 104 105 106]]


In [ ]:
np.linalg.det(arr)

2.4233807008391215e-27

In [ ]:
np.linalg.inv(arr)

array([[ 2.34562481e+13, -8.66990291e+00, -7.03687442e+13,
         4.69124961e+13],
       [-2.86669922e+00, -7.03687442e+13,  1.40737488e+14,
        -7.03687442e+13],
       [-7.03687442e+13,  1.40737488e+14, -7.03687442e+13,
        -0.00000000e+00],
       [ 4.69124961e+13, -7.03687442e+13, -0.00000000e+00,
         2.34562481e+13]])